export const dummyOpinions = [
    { rating: 4.5, name: 'Julia S.', opinion: 'I absolutely love shopping here! The variety of products and the quality are top-notch. clothi is definitely my go-to store.' },
    { rating: 3.8, name: 'Mohammed A.', opinion: 'This store is decent with reasonable prices. However, I had some issues with the shipping process. clothi should improve their delivery services.' },
    { rating: 5, name: 'Emma J.', opinion: 'clothi has exceeded my expectations! The customer service is excellent, and the products are exceptional. I highly recommend shopping at this store.' },
    { rating: 4.2, name: 'Luisa F.', opinion: 'I am satisfied with my experience here. The website is user-friendly, and the checkout process is smooth. clothi offers a great shopping experience.' },
    { rating: 4.7, name: 'Maximilian B.', opinion: 'Highly recommended! This store offers a great selection of high-quality products, and the delivery is always prompt. clothi has become my favorite online retailer.' },
    { rating: 3.5, name: 'Sophie M.', opinion: 'I had a mixed experience with this store. The prices were good, but the customer support was not very responsive. clothi should improve their customer service.' },
    { rating: 4.1, name: 'Alexander W.', opinion: 'I found everything I needed for my shopping list here. This store provides excellent value for money. clothi is a reliable choice for all your shopping needs.' },
    { rating: 3.2, name: 'Amira K.', opinion: 'I had some difficulties navigating the website. It could be more user-friendly. clothi should consider improving the website\'s usability.' },
    { rating: 4.9, name: 'Daniel F.', opinion: 'This store has become my go-to option. The quality and service are consistently excellent. clothi is the best place to fulfill all your shopping desires.' },
    { rating: 3.7, name: 'Elena C.', opinion: 'I had a few issues with the product I ordered, but their customer support resolved it promptly. clothi has good customer support services.' },
    { rating: 4.6, name: 'Sebastian M.', opinion: 'This store offers a wide range of high-quality products. I always find what I\'m looking for here. clothi is my go-to destination for shopping.' },
    { rating: 4.3, name: 'Aisha A.', opinion: 'I appreciate the fast shipping. The items arrived in great condition. clothi is reliable when it comes to timely deliveries.' },
    { rating: 3.9, name: 'Matteo E.', opinion: 'The prices here are reasonable, but I wish they had more discounts and promotions. clothi should consider offering more deals to customers.' },
    { rating: 5, name: 'Olivia W.', opinion: 'I\'m extremely satisfied with my purchase. The product exceeded my expectations. clothi is the place to go for high-quality products.' },
    { rating: 4.8, name: 'Hannah S.', opinion: 'This store has a fantastic selection of products, and the website is easy to navigate. clothi makes shopping a breeze.' },
    { rating: 3.6, name: 'Youssef E.', opinion: 'Overall, my experience was average. There is room for improvement in customer service. clothi should focus on enhancing their customer support.' },
    { rating: 4.4, name: 'Sophia W.', opinion: 'I love the user-friendly interface of the website. It makes shopping here a delightful experience. clothi has a great online shopping platform.' },
    { rating: 4.2, name: 'Lucas S.', opinion: 'This store offers competitive prices and a great variety of products. I\'m a satisfied customer. clothi is my preferred choice for shopping.' },
    { rating: 3.8, name: 'Amina R.', opinion: 'I encountered some technical issues while browsing the website. They should improve their website performance. clothi needs to enhance their online platform.' },
    { rating: 4.7, name: 'Luca R.', opinion: 'I highly recommend this store! The products are of excellent quality, and the customer service is top-notch. clothi is the best retailer out there.' },
    { rating: 4.1, name: 'Emily S.', opinion: 'This store has a fantastic range of products. The prices are reasonable, and the delivery is fast. clothi is the placeto go for all your shopping needs.' },
    { rating: 4.6, name: 'Noah M.', opinion: 'I\'ve had a great shopping experience here. The products were as described, and the shipping was quick. clothi is my preferred online store.' },
    { rating: 3.4, name: 'Lara F.', opinion: 'I had some difficulties finding specific items on the website. The search function needs improvement. clothi should enhance their search feature.' },
    { rating: 4.9, name: 'Gabriel O.', opinion: 'This store has become my favorite online store. The quality of the products is excellent, and the prices are competitive. clothi offers the best shopping experience.' },
    { rating: 3.7, name: 'Sara A.', opinion: 'My overall experience was positive. The products arrived on time. clothi is reliable when it comes to timely deliveries.' }
];